main-menu: parallax-bg.o buttons.o

parallax-bg.o: parallax-bg.c parallax-bg.h
	$(CC) $(CCFLAGS) -o parallax-bg.o parallax-bg.c $(LIBS)

buttons.o: buttons.c buttons.h
	$(CC) $(CCFLAGS) -o buttons.o buttons.c $(LIBS)
